spring.application.name=gestao-custos

# 01:20:00
# =============== Configurações H2  ===============#
spring.datasource.url=jdbc:h2:file:./data/gestao-despesa
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
sprign.datasource.database-platform=org.hibernate.dialet.H2Dialect

# 01:25:45
spring.jpa.hibernate.ddl-auto=update
